login = "//a[@class='_1_3w1N']"
enter_mmobile_number = "//input[@class='_2IX_2- VJZDxU']"
enter_password = "//input[@class='_2IX_2- _3mctLh VJZDxU']"
enter_submit = "/button[@class='_2KpZ6l _2HKlqd _3AWRsL']"
search_box = "//input[@name='q']"
submit_button ="//button[@type='submit']"
short_price = "//div[@class='_2b0bUo']/div[3]/select"
select_brand_name = "//*[@id='container']/div/div[3]/div/div[1]/div/div[1]/div/section[3]/div[2]/div[1]/div[2]/div/label/div[1]"
select_first_item = "/html/body/div/div/div[3]/div/div[2]/div[2]/div/div/div/a/div[2]/div[1]/div[1]"
click_buy_now = "//button[@class='_2KpZ6l _2U9uOA ihZ75k _3AWRsL']"
delevery_here = "//button[@class='_2KpZ6l RLM7ES _3AWRsL']"
continue_here = "//button[@class='_2KpZ6l _1seccl _3AWRsL']"
select_credit_card = "//input[@id='CREDIT']"
enter_card_number = "//input[@name='cardNumber']"
select_month = "//select[@name='month']"
select_year = "/select[@name='year']"
select_cvv = "//input[@name='cvv']"
pay_ammount = "//button[@class='_2KpZ6l _2nejCf _3AWRsL']"
